In [1]:
import pandas as pd
nykaa_df=pd.read_csv('data/nykaa_campaign_data_with_nulls.csv')
purplle_df=pd.read_csv('data/purplle_campaign_data_with_nulls.csv')
tira_df=pd.read_csv('data/tira_campaign_data_with_nulls.csv')

In [2]:
print("Nykaa:", nykaa_df.shape)
print("Purplle:", purplle_df.shape)
print("Tira:", tira_df.shape)

Nykaa: (55555, 16)
Purplle: (55555, 16)
Tira: (55555, 16)

In [3]:
nykaa_df.head()

,Campaign_ID,Campaign_Type,Target_Audience,Duration,Channel_Used,Impressions,Clicks,Leads,Conversions,Revenue,Acquisition_Cost,ROI,Language,Engagement_Score,Customer_Segment,Date
0,NY-CMP-1000,Social Media,College Students,21.0,"WhatsApp, YouTube",57804.0,6156.0,3616.0,2355.0,1867515.0,NaN,6.14,Hindi,20.98,College Students,29-04-2025
1,NY-CMP-1001,Paid Ads,Tier 2 City Customers,18.0,YouTube,91801.0,3321.0,1971.0,1357.0,1046247.0,180.83,3.26,Hindi,7.24,College Students,06-04-2025
2,NY-CMP-1002,Influencer,Youth,23.0,"WhatsApp, Google, YouTube",15536.0,2182.0,952.0,755.0,197055.0,90.60,NaN,English,25.03,College Students,14-01-2025
3,NY-CMP-1003,Email,Working Women,18.0,"YouTube, Facebook, Instagram",88114.0,8413.0,2231.0,947.0,376906.0,249.07,0.60,Hindi,13.15,NaN,04-06-2025
4,NY-CMP-1004,Paid Ads,College Students,10.0,"Facebook, Instagram",96871.0,3743.0,2060.0,1258.0,518296.0,228.60,0.80,Hindi,7.29,Tier 2 City Customers,29-12-2024

In [4]:
purplle_df.head()

,Campaign_ID,Campaign_Type,Target_Audience,Duration,Channel_Used,Impressions,Clicks,Leads,Conversions,Revenue,Acquisition_Cost,ROI,Language,Engagement_Score,Customer_Segment,Date
0,PU-CMP-1000,Paid Ads,Working Women,6.0,"Facebook, Google",31869.0,3490.0,1946.0,902.0,493394.0,55.93,8.78,Tamil,19.89,Premium Shoppers,27-12-2024
1,PU-CMP-1001,Paid Ads,Premium Shoppers,8.0,"Instagram, WhatsApp",26640.0,2441.0,741.0,314.0,108644.0,197.44,0.75,Bengali,13.12,NaN,26-11-2024
2,PU-CMP-1002,Influencer,Youth,22.0,"Facebook, WhatsApp",36967.0,4997.0,1025.0,653.0,NaN,234.59,0.56,NaN,18.06,College Students,08-01-2025
3,PU-CMP-1003,Paid Ads,Youth,15.0,"Instagram, WhatsApp",73258.0,5893.0,2565.0,1970.0,1341570.0,103.76,5.56,Bengali,14.23,College Students,14-03-2025
4,PU-CMP-1004,Social Media,Premium Shoppers,11.0,"WhatsApp, Instagram",91081.0,6393.0,3282.0,2582.0,787510.0,78.61,NaN,English,13.46,College Students,11-07-2024

In [5]:
tira_df.head()

,Campaign_ID,Campaign_Type,Target_Audience,Duration,Channel_Used,Impressions,Clicks,Leads,Conversions,Revenue,Acquisition_Cost,ROI,Language,Engagement_Score,Customer_Segment,Date
0,TI-CMP-1000,SEO,Working Women,11.0,NaN,64004.0,2906.0,1639.0,952.0,222768.0,129.72,0.80,Tamil,NaN,Premium Shoppers,30-10-2024
1,TI-CMP-1001,Social Media,Tier 2 City Customers,24.0,YouTube,71795.0,2051.0,552.0,256.0,199168.0,316.36,1.46,Tamil,3.98,College Students,11-09-2024
2,TI-CMP-1002,NaN,Working Women,28.0,NaN,79158.0,3546.0,1928.0,1314.0,433620.0,NaN,2.62,English,8.58,Tier 2 City Customers,28-08-2024
3,TI-CMP-1003,Email,Youth,8.0,Google,31523.0,3721.0,2088.0,736.0,571872.0,161.13,3.82,Bengali,20.76,Youth,27-07-2024
4,TI-CMP-1004,Paid Ads,Premium Shoppers,15.0,"Facebook, Email, WhatsApp",61441.0,7277.0,3615.0,2602.0,1477936.0,82.07,NaN,Tamil,21.96,College Students,19-12-2024

In [6]:
tira_df.columns.tolist()

['Campaign_ID',
 'Campaign_Type',
 'Target_Audience',
 'Duration',
 'Channel_Used',
 'Impressions',
 'Clicks',
 'Leads',
 'Conversions',
 'Revenue',
 'Acquisition_Cost',
 'ROI',
 'Language',
 'Engagement_Score',
 'Customer_Segment',
 'Date']

In [7]:
nykaa_df.columns.tolist() == purplle_df.columns.tolist()
nykaa_df.columns.tolist() == tira_df.columns.tolist()

True

In [8]:
print("NYKAA COLUMNS:")
print(nykaa_df.columns.tolist())

print("\nPURPLLE COLUMNS:")
print(purplle_df.columns.tolist())

print("\nTIRA COLUMNS:")
print(tira_df.columns.tolist())

NYKAA COLUMNS:
['Campaign_ID', 'Campaign_Type', 'Target_Audience', 'Duration', 'Channel_Used', 'Impressions', 'Clicks', 'Leads', 'Conversions', 'Revenue', 'Acquisition_Cost', 'ROI', 'Language', 'Engagement_Score', 'Customer_Segment', 'Date']

PURPLLE COLUMNS:
['Campaign_ID', 'Campaign_Type', 'Target_Audience', 'Duration', 'Channel_Used', 'Impressions', 'Clicks', 'Leads', 'Conversions', 'Revenue', 'Acquisition_Cost', 'ROI', 'Language', 'Engagement_Score', 'Customer_Segment', 'Date']

TIRA COLUMNS:
['Campaign_ID', 'Campaign_Type', 'Target_Audience', 'Duration', 'Channel_Used', 'Impressions', 'Clicks', 'Leads', 'Conversions', 'Revenue', 'Acquisition_Cost', 'ROI', 'Language', 'Engagement_Score', 'Customer_Segment', 'Date']

In [9]:
nykaa_df["Brand"] = "Nykaa"
purplle_df["Brand"] = "Purplle"
tira_df["Brand"] = "Tira"

In [10]:
nykaa_df.head()

,Campaign_ID,Campaign_Type,Target_Audience,Duration,Channel_Used,Impressions,Clicks,Leads,Conversions,Revenue,Acquisition_Cost,ROI,Language,Engagement_Score,Customer_Segment,Date,Brand
0,NY-CMP-1000,Social Media,College Students,21.0,"WhatsApp, YouTube",57804.0,6156.0,3616.0,2355.0,1867515.0,NaN,6.14,Hindi,20.98,College Students,29-04-2025,Nykaa
1,NY-CMP-1001,Paid Ads,Tier 2 City Customers,18.0,YouTube,91801.0,3321.0,1971.0,1357.0,1046247.0,180.83,3.26,Hindi,7.24,College Students,06-04-2025,Nykaa
2,NY-CMP-1002,Influencer,Youth,23.0,"WhatsApp, Google, YouTube",15536.0,2182.0,952.0,755.0,197055.0,90.60,NaN,English,25.03,College Students,14-01-2025,Nykaa
3,NY-CMP-1003,Email,Working Women,18.0,"YouTube, Facebook, Instagram",88114.0,8413.0,2231.0,947.0,376906.0,249.07,0.60,Hindi,13.15,NaN,04-06-2025,Nykaa
4,NY-CMP-1004,Paid Ads,College Students,10.0,"Facebook, Instagram",96871.0,3743.0,2060.0,1258.0,518296.0,228.60,0.80,Hindi,7.29,Tier 2 City Customers,29-12-2024,Nykaa

In [11]:
df = pd.concat(
    [nykaa_df, purplle_df, tira_df],
    ignore_index=True
)

In [12]:
df.head()

,Campaign_ID,Campaign_Type,Target_Audience,Duration,Channel_Used,Impressions,Clicks,Leads,Conversions,Revenue,Acquisition_Cost,ROI,Language,Engagement_Score,Customer_Segment,Date,Brand
0,NY-CMP-1000,Social Media,College Students,21.0,"WhatsApp, YouTube",57804.0,6156.0,3616.0,2355.0,1867515.0,NaN,6.14,Hindi,20.98,College Students,29-04-2025,Nykaa
1,NY-CMP-1001,Paid Ads,Tier 2 City Customers,18.0,YouTube,91801.0,3321.0,1971.0,1357.0,1046247.0,180.83,3.26,Hindi,7.24,College Students,06-04-2025,Nykaa
2,NY-CMP-1002,Influencer,Youth,23.0,"WhatsApp, Google, YouTube",15536.0,2182.0,952.0,755.0,197055.0,90.60,NaN,English,25.03,College Students,14-01-2025,Nykaa
3,NY-CMP-1003,Email,Working Women,18.0,"YouTube, Facebook, Instagram",88114.0,8413.0,2231.0,947.0,376906.0,249.07,0.60,Hindi,13.15,NaN,04-06-2025,Nykaa
4,NY-CMP-1004,Paid Ads,College Students,10.0,"Facebook, Instagram",96871.0,3743.0,2060.0,1258.0,518296.0,228.60,0.80,Hindi,7.29,Tier 2 City Customers,29-12-2024,Nykaa

In [13]:
df.tail()

,Campaign_ID,Campaign_Type,Target_Audience,Duration,Channel_Used,Impressions,Clicks,Leads,Conversions,Revenue,Acquisition_Cost,ROI,Language,Engagement_Score,Customer_Segment,Date,Brand
166660,NaN,NaN,Tier 2 City Customers,11.0,"Instagram, YouTube, Email",NaN,3799.0,NaN,1099.0,454986.0,213.21,0.94,Bengali,10.70,Youth,12-11-2024,Tira
166661,TI-CMP-56551,SEO,Working Women,20.0,"Google, Instagram",54886.0,1578.0,634.0,NaN,136514.0,436.24,-0.09,English,4.66,Working Women,25-08-2024,Tira
166662,TI-CMP-56552,Email,NaN,13.0,"Facebook, Instagram",97954.0,11480.0,4567.0,2144.0,445952.0,78.77,1.64,NaN,18.57,Premium Shoppers,15-04-2025,Tira
166663,NaN,Influencer,Premium Shoppers,22.0,"Google, Email",11669.0,NaN,122.0,44.0,26884.0,NaN,-0.76,English,5.35,Working Women,21-07-2024,Tira
166664,TI-CMP-56554,Paid Ads,Working Women,NaN,Instagram,50497.0,1604.0,542.0,363.0,281688.0,151.44,4.12,English,4.97,Premium Shoppers,02-05-2025,Tira

In [14]:
df.shape

(166665, 17)

In [15]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 166665 entries, 0 to 166664
Data columns (total 17 columns):
 #   Column            Non-Null Count   Dtype
---  ------            --------------   -----
 0   Campaign_ID       161248 non-null  str
 1   Campaign_Type     158307 non-null  str
 2   Target_Audience   158493 non-null  str
 3   Duration          158342 non-null  float64
 4   Channel_Used      158383 non-null  str
 5   Impressions       158441 non-null  float64
 6   Clicks            158441 non-null  float64
 7   Leads             158575 non-null  float64
 8   Conversions       158665 non-null  float64
 9   Revenue           158361 non-null  float64
 10  Acquisition_Cost  158504 non-null  float64
 11  ROI               158367 non-null  float64
 12  Language          158366 non-null  str
 13  Engagement_Score  158584 non-null  float64
 14  Customer_Segment  158490 non-null  str
 15  Date              158566 non-null  str
 16  Brand             166665 non-null  str
dtypes: float64(9), str(8)
memory usage: 34.8 MB

In [16]:
df.isnull().sum()

Campaign_ID         5417
Campaign_Type       8358
Target_Audience     8172
Duration            8323
Channel_Used        8282
Impressions         8224
Clicks              8224
Leads               8090
Conversions         8000
Revenue             8304
Acquisition_Cost    8161
ROI                 8298
Language            8299
Engagement_Score    8081
Customer_Segment    8175
Date                8099
Brand                  0
dtype: int64

In [17]:
df.duplicated().sum()

np.int64(0)

In [18]:
df["Campaign_Type"].unique()

<ArrowStringArray>
['Social Media', 'Paid Ads', 'Influencer', 'Email', nan, 'SEO']
Length: 6, dtype: str

In [19]:
categorical_columns = [
    "Campaign_Type",
    "Target_Audience",
    "Channel_Used",
    "Language",
    "Customer_Segment",
    "Brand"
]

for column in categorical_columns:
    print(f"\n{column}:")
    print(df[column].unique()[:20])

Campaign_Type:
<ArrowStringArray>
['Social Media', 'Paid Ads', 'Influencer', 'Email', nan, 'SEO']
Length: 6, dtype: str

Target_Audience:
<ArrowStringArray>
[     'College Students', 'Tier 2 City Customers',                 'Youth',
         'Working Women',      'Premium Shoppers',                     nan]
Length: 6, dtype: str

Channel_Used:
<ArrowStringArray>
[           'WhatsApp, YouTube',                      'YouTube',
    'WhatsApp, Google, YouTube', 'YouTube, Facebook, Instagram',
          'Facebook, Instagram',             'Email, Instagram',
    'YouTube, Google, WhatsApp',                            nan,
    'Facebook, WhatsApp, Email',                        'Email',
            'Facebook, YouTube',   'Email, Instagram, Facebook',
                    'Instagram',   'Facebook, Instagram, Email',
                     'WhatsApp',   'Google, YouTube, Instagram',
              'Google, YouTube',   'Instagram, YouTube, Google',
      'Google, Email, WhatsApp',            'YouTube, Facebook']
Length: 20, dtype: str

Language:
<ArrowStringArray>
['Hindi', 'English', nan, 'Tamil', 'Bengali']
Length: 5, dtype: str

Customer_Segment:
<ArrowStringArray>
[     'College Students',                     nan, 'Tier 2 City Customers',
      'Premium Shoppers',                 'Youth',         'Working Women']
Length: 6, dtype: str

Brand:
<ArrowStringArray>
['Nykaa', 'Purplle', 'Tira']
Length: 3, dtype: str

In [20]:
df.dtypes

Campaign_ID             str
Campaign_Type           str
Target_Audience         str
Duration            float64
Channel_Used            str
Impressions         float64
Clicks              float64
Leads               float64
Conversions         float64
Revenue             float64
Acquisition_Cost    float64
ROI                 float64
Language                str
Engagement_Score    float64
Customer_Segment        str
Date                    str
Brand                   str
dtype: object

In [21]:
df.describe()

,Duration,Impressions,Clicks,Leads,Conversions,Revenue,Acquisition_Cost,ROI,Engagement_Score
count,158342.000000,158441.000000,158441.000000,158575.000000,158665.000000,1.583610e+05,158504.000000,158367.00000,158584.000000
mean,17.488582,55068.759456,4684.973978,1872.167157,1028.498213,5.138267e+05,376.830560,2.69620,13.764843
std,7.501765,25961.688169,3177.355919,1430.272768,857.687806,4.875933e+05,536.701697,4.48544,6.328162
min,5.000000,10001.000000,202.000000,48.000000,17.000000,3.895000e+03,8.180000,-0.99000,2.560000
25%,11.000000,32599.000000,2110.000000,779.000000,401.000000,1.775800e+05,106.760000,0.05000,8.380000
50%,17.000000,55113.000000,3908.000000,1476.000000,775.000000,3.588720e+05,208.725000,1.24000,13.590000
75%,24.000000,77582.000000,6695.000000,2600.000000,1403.000000,6.856400e+05,428.560000,3.58000,18.790000
max,30.000000,100000.000000,14944.000000,8876.000000,6686.000000,4.579910e+06,15473.160000,79.30000,30.990000

In [22]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 166665 entries, 0 to 166664
Data columns (total 17 columns):
 #   Column            Non-Null Count   Dtype
---  ------            --------------   -----
 0   Campaign_ID       161248 non-null  str
 1   Campaign_Type     158307 non-null  str
 2   Target_Audience   158493 non-null  str
 3   Duration          158342 non-null  float64
 4   Channel_Used      158383 non-null  str
 5   Impressions       158441 non-null  float64
 6   Clicks            158441 non-null  float64
 7   Leads             158575 non-null  float64
 8   Conversions       158665 non-null  float64
 9   Revenue           158361 non-null  float64
 10  Acquisition_Cost  158504 non-null  float64
 11  ROI               158367 non-null  float64
 12  Language          158366 non-null  str
 13  Engagement_Score  158584 non-null  float64
 14  Customer_Segment  158490 non-null  str
 15  Date              158566 non-null  str
 16  Brand             166665 non-null  str
dtypes: float64(9), str(8)
memory usage: 34.8 MB

In [23]:
df.isnull().sum()

Campaign_ID         5417
Campaign_Type       8358
Target_Audience     8172
Duration            8323
Channel_Used        8282
Impressions         8224
Clicks              8224
Leads               8090
Conversions         8000
Revenue             8304
Acquisition_Cost    8161
ROI                 8298
Language            8299
Engagement_Score    8081
Customer_Segment    8175
Date                8099
Brand                  0
dtype: int64